services:
  web:
    environment:
      RAILS_ENV: development
      BUNDLE_WITHOUT: "test"
    command: bash -c "bundle exec rails db:prepare && bin/dev"
    volumes:
      - .:/rails    # code-mount para hot reload
