version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

  web:
    env_file: .env
    build: .
    depends_on:
      - db
      - redis
    # ─────────────── ENV vars ───────────────
    environment:
      RAILS_ENV: production
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: "${REDIS_URL}"
      RAILS_SERVE_STATIC_FILES: "true"   # Rails expõe /public
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"  # ou monte do host
    # ─────────────── Volumes úteis ───────────────
    volumes:
      - ./storage:/rails/storage         # ActiveStorage
      - ./log:/rails/log                 # logs persistentes
    expose:
      - "3000"
    command: ./bin/rails server -b 0.0.0.0 -p 3000

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  db_data:
