name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
      redis:
        image: redis:7
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.8"
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Prepare DB
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
        run: bin/rails db:prepare

      - name: Run tests
        run: bin/rails test # ou bundle exec rspec, se trocar para RSpec
